#!/usr/bin/env zsh

i3-msg "workspace www;append_layout $XDG_CONFIG_HOME/i3/ws_www.json"
(google-chrome-stable &)

i3-msg "workspace sys;append_layout $XDG_CONFIG_HOME/i3/ws_sys.json"
(urxvt &)

i3-msg "workspace dev;append_layout $XDG_CONFIG_HOME/i3/ws_dev.json"
(urxvt -name console -cd ~/projects/ &)
(urxvt -name console -cd ~/projects/ &)

i3-msg "workspace sys;workspace www"

