#!/bin/sh

userresources=$XDG_CONFIG_HOME/X11/Xresources
usermodmap=$XDG_CONFIG_HOME/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap


# source system defaults
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


# configure virtual displays
xrandr --output HDMI-0 --mode 5120x1440
xrandr --setmonitor HDMI-0-1 1280/298x1440/336+0+0 HDMI-0
xrandr --setmonitor HDMI-0-2 2560/597x1440/336+1280+0 none
xrandr --setmonitor HDMI-0-3 1280/298x1440/336+3840+0 none

# start apps
sh "$XDG_CONFIG_HOME/feh/wallpaper"

exec i3

