#!/usr/bin/env bash

userresources="${XDG_CONFIG_HOME}/X11/Xresources"
usermodmap="${XDG_CONFIG_HOME}/X11/Xmodmap"
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# source system defaults
if [ -f "$sysresources" ]; then
    xrdb -merge "$sysresources"
fi
if [ -f "$sysmodmap" ]; then
    xmodmap "$sysmodmap"
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"

fi
if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# import x11 variables into systemd user session
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

# configure virtual displays
bash "${HOME}/scripts/monitor-split"

# disable dpms
xset s 0 0 s noblank s noexpose s off

# start apps
bash "${XDG_CONFIG_HOME}/feh/wallpaper"
picom -b

exec i3

